version: '3.7'
services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pw1234
      POSTGRES_DB: mi-base-de-datos
    ports:
      - 5432:5432
